DanException: Refactor errors into static methods
Currently, DanException is thrown with custom messages when certain
error conditions are met. As the code base grows, the conditions
which may trigger these errors become hard to read, and the reader
must reverse engineer the code to figure out what causes these
errors.

Extracting these common behavior into static methods with magic
strings help to improve the readability of the code, in line with
the DRY and SLAP principles.

These makes the code more declarative and readable, while at the
same time, reduce human error by declaring error messages into a
single static final String.